spring:
    datasource:
        name: itk
        url: jdbc:mysql://localhost:3306/itk?useUnicode=true&characterEncoding=utf8
        username: root
        password: '!QAZxsw2'
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    application:
        name: itk-center

itk:
  solr:
    url: http://localhost:8983/solr/core1
    maxRetries: 3
    connectionTimeout: 500
  async:
    asyncCorePoolSize: 2
    asyncMaxPoolSize: 50
    queueCapacity: 10000